= Development Log

== Installation

=== Generate directory
`npx sv create mocap-svelte`

----
┌  Welcome to the Svelte CLI! (v0.8.10)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  prettier, eslint, vitest, playwright
│
◆  Successfully setup add-ons
│
◇  Which package manager do you want to install dependencies with?
│  npm
│
◆  Successfully installed dependencies
│
◇  Successfully formatted modified files
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: cd mocap-svelte                                                      │
│  2: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  3: npm run dev -- --open                                                │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
└  You're all set!
----
=== Initialize git repo

* `git config user.email "glick094@umn.edu"`
* `git config user.name "glick094"`
* `git init && git add -A && git commit -m "Initial commit"`
* `git remote add origin git@github.com:glick094/mocap-svelte.git`
* `git push -u origin main`
* `git branch -M install-threejs`
* `git checkout install-threejs`

==== Initialize github pages deployment

* `.github/workflows/deploy.yml`

=== Install SvelteKit for static site generation

* `npm install -D @sveltejs/adapter-static`
* update `svelte.config.js`

=== Install ThreeJS

* `npm install three`
* `npm install -D @types/three`

=== Install Mediapipe

* `npm install @mediapipe/holistic @mediapipe/camera_utils @mediapipe/drawing_utils`

== Next steps: 

* continue updating target csv outputs. 
* have the webcam inverted horizontally so the threejs is not mirrored
* add qr reader for inputting participant data