= Development Log

== Installation

=== Generate directory
`npx sv create mocap-svelte`

----
┌  Welcome to the Svelte CLI! (v0.8.10)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  prettier, eslint, vitest, playwright
│
◆  Successfully setup add-ons
│
◇  Which package manager do you want to install dependencies with?
│  npm
│
◆  Successfully installed dependencies
│
◇  Successfully formatted modified files
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: cd mocap-svelte                                                      │
│  2: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  3: npm run dev -- --open                                                │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
└  You're all set!
----
=== Initialize git repo

* `git config user.email "glick094@umn.edu"`
* `git config user.name "glick094"`
* `git init && git add -A && git commit -m "Initial commit"`
* `git remote add origin git@github.com:glick094/mocap-svelte.git`
* `git push -u origin main`
* `git branch -M install-threejs`
* `git checkout install-threejs`

==== Initialize github pages deployment

* `.github/workflows/deploy.yml`

=== Install SvelteKit for static site generation

* `npm install -D @sveltejs/adapter-static`
* update `svelte.config.js`

=== Install ThreeJS

* `npm install three`
* `npm install -D @types/three`

=== Install Mediapipe

* `npm install @mediapipe/holistic @mediapipe/camera_utils @mediapipe/drawing_utils`

== Knee movement

more force generation 
don't want coordination task to measure strength

height & handedness & 

what provide info about coordination? 

different ways we can look at coordination: 
1. able to organize body segments in relation to environment/obstacles in a smooth way
2. trajectory of movement
3. self organizing nature - adapt to new movement patterns

for hands the background 

hula hoops
yellow boxes with bubbles that move

-- this thing doesn't look like me! -- if we can get this more character

== Next steps: 

* [x] continue updating target csv outputs. 
* [x] have the webcam inverted horizontally so the threejs is not mirrored
* [x] add qr reader for inputting participant data
** [ ] fix the qr reader so it actually scans
* [x] the flow mode is not showing hands after centering
* [x] the flow mode is not showing head trials (shows hands)
* [x] the flow mode is not showing random trials
* [x] add a visual circle timer in short delay
* [ ] remove initial delay??
* [ ] update saving, so it includes participant ID correctly, 
* [ ] add pop-up box for participant ID if not added
* [ ] fix errors/warnings from `npm run check` ()
// - Session 1: 483 → 463 (20 errors)
// - Session 2: 463 → 374 (89 errors)
// - Session 3: 374 → 282 (92 errors)
// - Session 4: 282 → 243 (39 errors)
// - Session 5: 243 → 175 (68 errors)
// - Session 6: 175 → 135 (40 errors)
* [ ] hand trials, start with dominate (one they hit first, then second time will be other hand)
* [ ] add enjoyment scale "game/survey"

== Analysis Next Steps: 

* [ ] add signal to noise ratio

* [ ] add 15-20 seconds for wait time
* [ ] edit the descriptions - for what we want - have descriptions in shareable doc

* [ ] give them a box to do the task in 

* [ ] layout center line and trigger crosshairs 